site_name: RAAD EHR ROADMAP
site_url: https://uat.raad.gov.so
nav:
  - Home: index.md
  - Roadmap: home.md
  - About: about.md


theme:
   name: material
   logo: images/raad-logo.png
   features:
      - navigation.tabs
      - navigation.sections
      - toc.integrate
      - navigation.top
      - search.suggest
      - search.highlight
      - content.tabs.link
      - content.code.annotation
      - content.code.copy
   language: en
   palette:
     - scheme: default
       toggle:
         icon: material/toggle-switch-off-outline 
         name: Switch to dark mode
       primary: bluegrey
       accent: lime 
     - scheme: slate 
       toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
       primary: bluegrey
       accent: lime
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Nomadilab
    - icon: fontawesome/brands/linkedin
      link: https://twitter.com/Nomadilab
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
extra_css:
  - custom.css


